# Generated by Django 4.0.2 on 2022-03-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_laptop_phone_tablet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'All Products', 'verbose_name_plural': 'All Products'},
        ),
        migrations.AddField(
            model_name='laptop',
            name='amountOfRam',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='memorySize',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='processor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='numberOfCameras',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='operatingsystem',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='screensize',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='operatingsystem',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='operatingsystem',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='dimensions',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
