# Generated by Django 4.0.2 on 2022-03-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_options_laptop_amountofram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='memorySize',
            field=models.IntegerField(null=True, verbose_name='Memory Capacity'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='amountOfRam',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='RAM Amount'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='memorySize',
            field=models.IntegerField(null=True, verbose_name='Memory Capacity'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='operatingsystem',
            field=models.CharField(max_length=100, null=True, verbose_name='Operating System'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='processor',
            field=models.CharField(max_length=100, null=True, verbose_name='Processor'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='dimensions',
            field=models.CharField(max_length=100, null=True, verbose_name='Dimensions'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='numberOfCameras',
            field=models.IntegerField(null=True, verbose_name='Number Of Cameras'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='operatingsystem',
            field=models.CharField(max_length=100, null=True, verbose_name='Operating System'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='screensize',
            field=models.CharField(max_length=100, null=True, verbose_name='Screen Resolution'),
        ),
        migrations.AlterField(
            model_name='product',
            name='averagecost',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datereleased',
            field=models.DateField(verbose_name='Date Released'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='review',
            name='datePosted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Posted'),
        ),
        migrations.AlterField(
            model_name='review',
            name='productRating',
            field=models.IntegerField(null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewContent',
            field=models.TextField(null=True, verbose_name='Content of Review'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='operatingsystem',
            field=models.CharField(max_length=100, null=True, verbose_name='Operating System'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='screensize',
            field=models.CharField(max_length=100, verbose_name='Screen Resolution'),
        ),
    ]
