# Generated by Django 4.0.2 on 2022-03-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_phone_memorysize_alter_laptop_amountofram_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptop',
            options={'verbose_name_plural': ' Laptops'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name_plural': ' Phones'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'All Products', 'verbose_name_plural': ' All Products'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='tablet',
            options={'verbose_name_plural': ' Tablets'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Tablet', 'Tablet'), ('Laptop', 'Laptop'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=100, null=True),
        ),
    ]
