# Generated by Django 4.0.2 on 2022-04-01 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='productRating',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Rating'),
        ),
    ]
