# Generated by Django 4.0.2 on 2022-04-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_review_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='preview',
            field=models.TextField(null=True),
        ),
    ]
